### ISSUE TITLE
Does not work in Node projects

### ISSUE THREAD

**Issue by CupOfTea696** [aesy/Easy-Bits#3]
Easy-bits does not work in Node projects since its distribution file is targeting browsers. Directly importing the source file does not work either, since this package is not defined as a module.

Normal import:

```js
// test.js
import eb from 'easy-bits'
```

```shell
$ node test.js

ReferenceError: window is not defined
    at Object.<anonymous> ([PATH]/node_modules/easy-bits/dist/easy-bits.min.js:1:224)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Source import:

```js
// test.js
import eb from 'easy-bits/src/index.js'
```

```shell
$ node test.js

(node:48430) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[PATH]/node_modules/easy-bits/src/index.js:1
import BitArray from './BitArray';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by aesy** [comment]
Hey, thanks for the report!

The real issue here is that the lib is built for CommonJS, not ES modules. The distributed bundle is an UMD module, which doesn't play nice with node with ES modules enabled. However, the following runs fine, even though the bundle references `window`:

```js
const { Enum } = require('easy-bits');
```

I will remove the `window` reference, but that wouldn't fix the main issue. I also can't mark the library as an ES module, because that would break all CommonJS projects. I'll instead look into creating two bundles, one for CommonJS and one for ES modules - this seems to be an experimental feature in the latest version of webpack.

**Comment by aesy** [comment]
A new version (`1.2.0`) with support for ES modules has been published!

I've made sure that the following works:

Run with Node using CommonJS:

```js
// index.js
const eb = require('easy-bits');
const { BitField } = require('easy-bits');
```
```sh
$ node index.js
```

Run with Node using ES modules:

```js
// index.mjs
import eb from 'easy-bits';
import { BitField } from 'easy-bits';
```
```sh
$ node index.mjs
```

Compile with TypeScript using CommonJS:

```js
// index.ts
import { BitField } from 'easy-bits';
```
```sh
$ tsc index.ts --module commonjs
```

Compile with TypeScript using ES modules:

```js
// index.ts
import { BitField } from 'easy-bits';
```
```sh
$ tsc index.ts --module esnext --moduleResolution node
```

Run in browser:

```html
// index.html
<script src="easy-bits.min.js"></script>
<script>
  // BitField is accessible on window
</script>
```

Let me know if there is anything I've missed!
